#! /bin/sh

# Autostart applications
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &
pgrep -x dunst > /dev/null || dunst &
pgrep -x picom > /dev/null || picom &
pgrep -x blueman-applet > /dev/null || blueman-applet &
# pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x lxqt-policykit-agent > /dev/null || lxqt-policykit-agent &
exec $HOME/.config/eww/scripts/launch-bar > /dev/null &
exec $HOME/.config/bspwm/scripts/set-wallpaper &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          15
bspc config top_padding          5
bspc config right_padding        5
bspc config left_padding         5
bspc config bottom_padding       5

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config ignore_ewmh_focus   true

