#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          15
bspc config top_padding         10
bspc config right_padding       10
bspc config left_padding        10
bspc config bottom_padding      10

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config ignore_ewmh_focus   true

# Autostart applications
pgrep -x picom > /dev/null || dunst &
pgrep -x picom > /dev/null || picom &
pgrep -x blueman-applet > /dev/null || blueman-applet &
# pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x lxqt-policykit-agent > /dev/null || lxqt-policykit-agent &
~/.config/eww/scripts/launch-bar > /dev/null &

exec $HOME/.config/bspwm/scripts/set-wallpaper &
