#! /usr/bin/env sh

# Script to blink the colon ':' char in the bar clock 

state_file=$HOME/.cache/eww_date_state
blink=$(cat $state_file)

if [[ $blink = "on" ]]; then
    echo $(date +'%H:%M')
    echo -n "off" > $state_file
else
    echo $(date +'%H %M')
    echo -n "on" > $state_file
fi
