#!/usr/bin/env sh

run_script() {
    exec $HOME/.config/eww/scripts/player-status > /dev/null &
}

if eww ping; then
    PID=$(ps | grep 'playerctl' | awk '{ print $1 }')
    echo $PID
    [[ -z PID ]] || kill $PID > /dev/null
    eww reload > /dev/null
else
    eww open-many left-bar center-bar right-bar > /dev/null 
fi

run_script
