#! /usr/bin/env sh

PID_FILE="/tmp/player-status-pid"

# (Re)start player-status script
[ -f "$PID_FILE" ] && kill $(cat $PID_FILE) > /dev/null 2>&1 
$HOME/.config/eww/scripts/player-status > /dev/null 2>&1 &
echo $! > $PID_FILE

if eww ping > /dev/null 2>&1 ; then
    eww reload > /dev/null 2>&1
else
    eww open-many left-bar center-bar right-bar > /dev/null 2>&1
fi

