#! /usr/bin/env sh

PID_FILE="/tmp/player-status-pid"

# (Re)start player-status script
[ -f "$PID_FILE" ] && kill $(cat $PID_FILE)
$HOME/.config/eww/scripts/player-status > /dev/null &
echo $! > $PID_FILE

if eww ping > /dev/null; then
    eww reload > /dev/null
else
    eww open-many left-bar center-bar right-bar > /dev/null 
fi

