#! /usr/bin/env bash

# Wrap the entire logic inside a function because variables
# declared inside a while read loop losts its value after 
# exiting the loop
gen_workspace_yuck () {
    wmctrl -d | awk '{ print $1" "$2 }' | \
    while read -r id status; do

        if [[ $status = '*' ]]; then
            btn_status='active'
        else
            wmctrl -l | grep --regexp "\s$id\s" > /dev/null && btn_status="occupied" || btn_status="inactive"
        fi

        yuck="(button :class \"$btn_status\" :onclick \"wmctrl -s  $id\" \"\")"
        echo -n $yuck
    done
}

xprop -spy -root _NET_CURRENT_DESKTOP | while read -r; do
    echo '(box :orientation "h" :class "workspaces" :halign "start" :vexpand true '"$(gen_workspace_yuck)"')'
done
